version: '3.8'

services:
  frontend:
    image: harri665/drop-frontend:latest
    ports:
      - "3006:80" # Serve the frontend on port 80
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    restart: always

  backend:
    image: harri665/drop-backend:latest
    ports:
      - "3007:3007"
    environment:
      - NODE_ENV=production
    restart: always
